name: Build and Push Docker Image
on:
  push:
    branches:
      - main
    paths:
      - 'version.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.7.1
        
      - name: Install yq (YAML processor)
        run: sudo apt-get install -y jq

      - name: Extract version
        id: get_version
        run: |
          VERSION=$(cat version.yml | grep '^version:' | awk '{print $2}')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Version found: $VERSION"
      
      - name: Get previous tag
        id: get_prev_tag
        run: |
          PREV_TAG=$(git tag --sort=-v:refname | head -n 2 | tail -n 1)
          echo "PREV_TAG=$PREV_TAG" >> $GITHUB_ENV
          echo "Previous tag: $PREV_TAG"

      - name: Get commit messages since last tag
        id: get_commits
        run: |
          if [ -n "${{ env.PREV_TAG }}" ]; then
            COMMITS=$(git log ${{ env.PREV_TAG }}..HEAD --pretty=format:"%h %s")
          else
            COMMITS=$(git log --pretty=format:"%h %s")
          fi
          echo "COMMITS=$COMMITS" >> $GITHUB_ENV
          echo "Commit messages since last tag: $COMMITS"

      - name: Log in to DockerHub
        uses: docker/login-action@v3.3.0
        with:
          registry: gitea.intron014.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v6.9.0
        with:
          push: true
          platforms: linux/amd64
          tags: |
            gitea.intron014.com/intron014/api.intron014.com:${{ env.VERSION }}
            gitea.intron014.com/intron014/api.intron014.com:latest
          labels: |
            org.opencontainers.image.description=${{ env.COMMITS }}
