name: Build and Push Docker Image

on:
  push:
    paths:
      - 'version.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.7.1

      - name: Install yq (YAML processor)
        run: sudo apt-get install -y jq

      - name: Extract version
        id: get_version
        run: |
          VERSION=$(cat version.yml | grep '^version:' | awk '{print $2}')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Version found: $VERSION"
      
      - name: Log in to DockerHub
        uses: docker/login-action@v3.3.0
        with:
          registry: gitea.intron014.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build n Push
        uses: docker/build-push-action@v6.9.0
        with:
          push: true
          platforms: |
            linux/amd64
          tags: |
            gitea.intron014.com/intron014/api.intron014.com:${{ env.VERSION }}
            gitea.intron014.com/intron014/api.intron014.com:latest